### ISSUE TITLE
課題

### ISSUE THREAD

**Issue by OR6107** [Kaito-sokuho/kaito-sokuho.github.io#28]
- [x] スマホ版の閉じるが直ってない？
- [x] スマホ版メニューの横に黒ぽち？
- [x] スマホ版 アイコン+文字
- [x] PC版 アイコン
- [x] スマホ版でのタイトル表示   例 : 「中学入試解 `<br>` 答速報」
- [x] 更新日 日付にitemprop要素
- [x] 他のSEO対策
- [x] スクロールバーの有り無しを統一したいのですが...
- [x] TwitterとLINEを横並び/Twitter-timeline 幅設定 
- [x] Twitter-timeline 文字の大きさ設定 (#16)
- [x] **new!!** 全ページのアイコンとタイトル文字 に aタグ (トップページの)
- [x] ヘッダーの色 赤？
---------
ちょっと違うけど追加
- [x] `honbun-tx` PCだけ表示 `smartphone-tx-index` スマホだけ表示 にしてくれますか？

**Comment by Nakano-oeno-oji** [comment]
タイトル表示は、やろうとしたけどうまくいかなかったという経緯があったりします...
cssいじるのがめんどくさかっただけなんですけど()

**Comment by OR6107** [comment]
わかります...

**Comment by OR6107** [comment]
思い付きでまとめました

**Comment by Nakano-oeno-oji** [comment]
> * [ ]  スマホ版の閉じるが直ってない？
> * [ ]  スマホ版メニューの横に黒ぽち？
> * [ ]  スマホ版 アイコン+文字
> * [ ]  PC版 アイコン
> * [ ]  スマホ版でのタイトル表示   例 : 「中学入試解 `<br>` 答速報」
> * [ ]  更新日 日付にitemprop要素
> * [ ]  他のSEO対策
> * [ ]  スクロールバーの有り無しを統一したいのですが...
> * [ ]  TwitterとLINEを横並び/Twitter-timeline 幅設定
> * [ ]  Twitter-timeline 文字の大きさ設定 (#16)
> * [ ]  **new!!** 全ページのアイコンとタイトル文字 に aタグ (トップページの)
> * [ ]  ヘッダーの色 赤？

**Comment by OR6107** [comment]
閉じるというのは，太さのことです

**Comment by OR6107** [comment]
確認したらTopページ以外，太かったです．

**Comment by Nakano-oeno-oji** [comment]
修正しました～

**Comment by OR6107** [comment]
ちょっと違うけど追加
- [ ] `honbun-tx` PCだけ表示 `smartphone-tx-index` スマホだけ表示 にしてくれますか？
