### ISSUE TITLE
50音 PC/スマホ

### ISSUE THREAD

**Issue by OR6107** [Kaito-sokuho/kaito-sokuho.github.io#37]
切り替えができてないかな
![image](https://user-images.githubusercontent.com/59076597/106391945-257d2400-6433-11eb-9a81-8023074810b6.png)

**Comment by Nakano-oeno-oji** [comment]
コードはあってるから、たぶんまだ反映されてないだけだと思う

**Comment by OR6107** [comment]
反映されたけど，直ってないと

**Comment by Nakano-oeno-oji** [comment]
![スクリーンショット 2021-02-01 021620](https://user-images.githubusercontent.com/73774163/106392029-b05f0f80-639c-11eb-8bcd-d1f3c6981aef.png)

**Comment by Nakano-oeno-oji** [comment]
...？

**Comment by OR6107** [comment]
... ?

**Comment by Nakano-oeno-oji** [comment]
![スクリーンショット 2021-02-01 021620](https://user-images.githubusercontent.com/73774163/106392109-de445400-639c-11eb-8839-00d78c743a8f.png)
...？

**Comment by Nakano-oeno-oji** [comment]
ローカルだと反映されてるから、コードはあってるはず...？

**Comment by OR6107** [comment]
確かめる

**Comment by OR6107** [comment]
これも #35 ラグだったのかな
