### ISSUE TITLE
確認と課題

### ISSUE THREAD

**Issue by OR6107** [Kaito-sokuho/kaito-sokuho.github.io#41]
完了済み
- [x] スマホ版の閉じるが直ってない？
- [x] スマホ版メニューの横に黒ぽち？
- [x] PC版 アイコン
- [x] `honbun-tx` PCだけ表示 `smartphone-tx-index` スマホだけ表示 にしてくれますか？
- [x] 全ページのアイコンとタイトル文字 に aタグ (トップページの)
- [x] スクロールバーの有り無しを統一したいのですが...
- [x] ヘッダーの色 赤？→元のまま
- [x] 他のSEO対策 →Google
- [x] スマホ版 アイコン+文字 →無理
- [x] Twitter-timeline 文字の大きさ設定 (#16) →無理
---------
確認 これどうなった
- [ ] 更新日 日付にitemprop要素 →本文中？
- [ ] TwitterとLINEを横並び/Twitter-timeline 幅設定 / LINEの余白 →幅の微調整
- [ ] スマホ版でのタイトル表示   例 : 「中学入試解 `<br>` 答速報」→？？
---------
課題
- [ ] Twitter カード 作成(Figma) #26 
- [ ] ファイル名変更 #27
- [ ] 変更の際のルール #40 
---------
更新終了に伴いクローズ

**Comment by Nakano-oeno-oji** [comment]
スマホ版のアイコンと文字はあきらめた
SEO対策はgoogle側でやる
文字の大きさ設定もあきらめた
Lineの下の余白はしゃあない

**Comment by OR6107** [comment]
更新日のやつ
本文中に<span> [日付]</span>じゃないの？

**Comment by Nakano-oeno-oji** [comment]
本文中だっけ...?
直しておいてもらえるとありがたいです。
